### ISSUE TITLE
Update rust version

### ISSUE THREAD

**Issue by bitwave** [apache/incubator-teaclave-trustzone-sdk#30]
Is it possible to lift the rust dependency from nightly-2019-07-08 to a newer version? This is two (!) years old?

**Comment by mssun** [comment]
Yes, what we should do is following:
- Port changes of the Rust std/compiler-builtin/etc to a recent versions
- Upgrade the toolchain requirements of Rust

This needs to be done at the same time because the std code can only be compiled in a certain range versions of the Rust toolchain. (E.g., if std use a new language feature, it needs to be compile with the newer toolchain)

**Comment by bitwave** [comment]
I tried to do this by myself, but I got stuck at the std lib parts, where many things are missing/changed from this old version to the new one. Many parts look like boilerplate code to me...

**Comment by mssun** [comment]
@bitwave the toolchains has been updated to nightly-2021-09-20. Thanks!
